---
name: publish next website
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "next"
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo and build scripts
        uses: actions/checkout@v4
        with:
          ref: "next"
      - name: Install tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall,just
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.WWWKEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install deps
        run: poetry install
      - name: Install apps
        run: cargo binstall skctl sk-ctrl sk-driver sk-tracer -y
      - name: Publish ACRL
        run: just publish-next acrl
      - name: Publish Simkube
        run: just publish-next simkube
